-- +goose Up


CREATE TABLE feeds (
  id UUID NOT NULL PRIMARY KEY(id),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  name VARCHAR(255) NOT NULL,
  url TEXT NOT NULL UNIQUE,
  user_id UUID NOT NULL FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
);

